### PR TITLE
Added ToJSON instances to types.

### PR DESCRIPTION
**Pull request by AndrewRademacher**
Addressing both #14 and my own need to dump the json responses from twitter into Postgres, I have added ToJSON instances to twitter types which create an isomorphism with the FromJSON instances.

### CODE REVIEW

**Comment by AndrewRademacher** [comment]
Also, now addresses the need for Data, Typeable, and Generic instances. #13

**Comment by AndrewRademacher** [comment]
Apologies for the somewhat confused list of changes in this PR as well as the reformatting, I wasn't aware that I was working on master. If you are only interested in some parts of these changes just let me know, and I'll split the commits back out into a new PR.

**Comment by himura** [comment]
I've merged  9be9611...60e6c8a, and released as twitter-types 0.6.1. Thanks!!

**Comment by AndrewRademacher** [comment]
I was under the impression that `308ca82` wasn't merged because it was only formatting.

**Pull request closed without merging**
